# Generated by Django 3.1.2 on 2020-10-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracctracc', '0002_auto_20201026_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_art',
            field=models.URLField(blank=True, null=True),
        ),
    ]
